[package]
name = "upfire"
version = "0.1.0"
authors = ["Tymoteusz Paul <puciek@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = {git = "https://github.com/amethyst/amethyst.git", branch = "master"}
